# Mensaje de bienvenida al usuario
print("Welcome to REYES_MEZA_ALAN_1207_PRACTICA_07OCT24.py")
print(" ")

print("REYES MEZA ALAN EDUARDO :   3W")  # INFO DE PRACTICA Y PROGRAMADOR 
print(" ")  # ESPACIO

# 1. Definición de Funciones
def my_function():
    """Imprime un mensaje simple desde la función."""
    print("Hello from a function")

my_function()  # Llama a la función para ejecutar su contenido

#2- Para llamar a una funcion, use la funcion nombrada y seguida de parentesis:
def my_function():
  print("Hello from a function")




